-- FOR TRANSACTION_ID 1
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=1
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=1
)
WHERE TRANSACTION_ID=1;

-- FOR TRANSACTION_ID 2
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=2
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=2
)
WHERE TRANSACTION_ID=2;

-- FOR TRANSACTION_ID 3
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=3
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=3
)
WHERE TRANSACTION_ID=3;

-- FOR TRANSACTION_ID 4
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=4
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=4
)
WHERE TRANSACTION_ID=4;

-- FOR TRANSACTION_ID 5
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=5
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=5
)
WHERE TRANSACTION_ID=5;

-- FOR TRANSACTION_ID 6
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=6
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=6
)
WHERE TRANSACTION_ID=6;

-- FOR TRANSACTION_ID 7
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=7
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=7
)
WHERE TRANSACTION_ID=7;

-- FOR TRANSACTION_ID 8
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=8
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=8
)
WHERE TRANSACTION_ID=8;


-- FOR TRANSACTION_ID 9
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=9
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=9
)
WHERE TRANSACTION_ID=9;

-- FOR TRANSACTION_ID 10
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=10
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=10
)
WHERE TRANSACTION_ID=10;

-- FOR TRANSACTION_ID 11
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=11
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=11
)
WHERE TRANSACTION_ID=11;

-- FOR TRANSACTION_ID 12
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=12
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=12
)
WHERE TRANSACTION_ID=12;

-- FOR TRANSACTION_ID 13
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=13
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=13
)
WHERE TRANSACTION_ID=13;

-- FOR TRANSACTION_ID 14
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=14
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=14
)
WHERE TRANSACTION_ID=14;

-- FOR TRANSACTION_ID 15
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=15
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=15
)
WHERE TRANSACTION_ID=15;

-- FOR TRANSACTION_ID 16
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=16
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=16
)
WHERE TRANSACTION_ID=16;


-- FOR TRANSACTION_ID 17
UPDATE FINANCIAL_TRANSACTIONS 
SET AMOUNT= (
	SELECT SUM(TOTAL_DUE)
	FROM (
		SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
		FROM PURCHASE_ORDERS PO 
			JOIN PURCHASE_ORDER_PRODUCTS POP ON PO.ORDER_ID=POP.ORDER_ID
			JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
		WHERE PO.TRANSACTION_ID=17
	) 
), PLACEMENT_DATE=(
	SELECT PO1.PLACEMENT_DATE
	FROM PURCHASE_ORDERS PO1
	WHERE PO1.TRANSACTION_ID=17
)
WHERE TRANSACTION_ID=17