
--TO GET ALL INFO OF  A SUPPLIER
SELECT S.SUPPLIER_ID,S.SUPPLIER_NAME,S.CITY,S.COUNTRY,S.URL,S.AVG_DELIVERY_TIME,P.ACCOUNT_NUMBER,P.ACCOUNT_HOLDER,P.BANK_NAME,
P.IBAN, L.STREET_ADDRESS,L.POSTAL_CODE,L.CITY AS PICKUP_LOC_CITY,L.COUNTRY AS PICKUP_LOC_COUNTRY,C.PHONE_NO,C.EMAIL
FROM SUPPLIERS S 
		JOIN PAYMENT_INFO P ON S.PAYMENT_INFO_ID=P.ID
		JOIN LOCATIONS L ON L.LOCATION_ID=S.PICKUP_LOCATION_ID
		JOIN (
		SELECT DISTINCT C1.OWNER_ID AS SUPPLIER_ID, C1.VALUE AS PHONE_NO, C2.VALUE AS EMAIL
		FROM CONTACTS C1 JOIN CONTACTS C2 ON (C1.OWNER_ID=C2.OWNER_ID	AND C1.TYPE <> C2.TYPE AND C1.TYPE='PHONE')
		) C ON C.SUPPLIER_ID=S.SUPPLIER_ID 
WHERE S.SUPPLIER_ID=5
ORDER BY S.SUPPLIER_ID
		

--TO GET PRODUCT CATALOGUE
SELECT SP.PRODUCT_ID, P.PRODUCT_NAME,P.CATEGORY,P.PRICE,P.WARRANTY,P.MANUFACTURER,P.CENTRAL_STOCK
FROM SUPPLIER_PRODUCT SP JOIN PRODUCTS P ON SP.PRODUCT_ID=P.PRODUCT_ID
WHERE SP.SUPPLIER_ID=4;

--TO GET THE LIST OF PURHCASE ORDERS TO A SUPPLIER
SELECT ORDER_ID, PLACEMENT_DATE,PICKUP_DATE
FROM PURCHASE_ORDERS
WHERE SUPPLIER_ID=2
ORDER BY ORDER_ID;


--TO GET THE DETAILS (FINANCIAL AND SHIPMENT RELATED INFO) OF A PURCHASE ORDER
SELECT *
FROM (
	SELECT ORDER_ID,PLACEMENT_DATE,PICKUP_DATE,TRANSACTION_ID,SHIPMENT_ID
	FROM PURCHASE_ORDERS
	WHERE SUPPLIER_ID=2 AND ORDER_ID=4
) PO 
	JOIN 
	(
	SELECT FT.TRANSACTION_ID, FT.METHOD, PI1.ACCOUNT_HOLDER AS SENT_FROM_ACOOUNT, PI2.ACCOUNT_HOLDER AS RECEIVED_TO_ACCOUNT,FT.STATUS, (FT.AMOUNT || ' ' || UPPER(FT.CURRENCY)) AS AMOUNT, FT.PLACEMENT_DATE AS PAYMENT_DATE
	FROM FINANCIAL_TRANSACTIONS FT 
		JOIN PAYMENT_INFO PI1 ON (FT.FROM_ACCOUNT=PI1.ID)
		JOIN PAYMENT_INFO PI2 ON (FT.TO_ACCOUNT=PI2.ID)
	--WHERE FT.TRANSACTION_ID=4
	) F USING(TRANSACTION_ID)--ON F.TRANSACTION_ID=PO.TRANSACTION_ID
	JOIN
	(
	SELECT S.SHIPMENT_ID,TC.NAME AS PICKED_UP_BY, (L1.STREET_ADDRESS||', '||L1.CITY|| ', '||L1.COUNTRY) AS PICKED_UP_FROM,(S.DEPARTURE_DATE) AS PICKED_UP_ON,(S.DEPARTURE_TIME) AS PICKED_UP_AT,(L2.STREET_ADDRESS||', '||L2.CITY|| ', '||L2.COUNTRY) AS RECEIVED_AT, (S.ARRIVAL_DATE) AS RECEIVED_ON, S.ARRIVAL_TIME AS RECEIVED_AT_TIME, S.VEHICLE_NO AS VEHICLE_USED, S.CURRENT_LOCATION
	FROM SHIPMENTS S 
		JOIN TRANSPORT_COMPANIES TC ON TC.COMPANY_ID=S.TRANSPORT_COMPANY_ID
		JOIN LOCATIONS L1 ON S.START_LOCATION=L1.LOCATION_ID
		JOIN LOCATIONS L2 ON S.DESTINATION=L2.LOCATION_ID
	) SI USING(SHIPMENT_ID)--ON SI.SHIPMENT_ID=PO.SHIPMENT_ID
	

--TO GET THE PURCHASED PRODUCT LIST IN A PURCHASE ORDER
SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE AS PRICE_EACH,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
FROM PURCHASE_ORDER_PRODUCTS POP 
	JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
WHERE POP.ORDER_ID=1



-- SELECT S.SHIPMENT_ID,TC.NAME AS PICKED_UP_BY, (L1.STREET_ADDRESS||', '||L1.CITY|| ', '||L1.COUNTRY) AS PICKED_UP_FROM,(S.DEPARTURE_DATE) AS PICKED_UP_ON,(S.DEPARTURE_TIME) AS PICKED_UP_AT,(L2.STREET_ADDRESS||', '||L2.CITY|| ', '||L2.COUNTRY) AS RECEIVED_AT, (S.ARRIVAL_DATE) AS RECEIVED_ON, S.ARRIVAL_TIME AS RECEIVED_AT_TIME, S.VEHICLE_NO AS VEHICLE_USED, S.CURRENT_LOCATION
-- FROM SHIPMENTS S 
-- 	JOIN TRANSPORT_COMPANIES TC ON TC.COMPANY_ID=S.TRANSPORT_COMPANY_ID
-- 	JOIN LOCATIONS L1 ON S.START_LOCATION=L1.LOCATION_ID
-- 	JOIN LOCATIONS L2 ON S.DESTINATION=L2.LOCATION_ID















-- SELECT FT.TRANSACTION_ID, FT.METHOD, PI1.ACCOUNT_HOLDER AS SENT_FROM_ACOOUNT, PI2.ACCOUNT_HOLDER AS RECEIVED_TO_ACCOUNT,FT.STATUS, (FT.AMOUNT || ' ' || UPPER(FT.CURRENCY)) AS AMOUNT
-- FROM FINANCIAL_TRANSACTIONS FT 
-- 	JOIN PAYMENT_INFO PI1 ON (FT.FROM_ACCOUNT=PI1.ID)
-- 	JOIN PAYMENT_INFO PI2 ON (FT.TO_ACCOUNT=PI2.ID)
-- WHERE FT.TRANSACTION_ID=4
-- 
-- 
-- SELECT TRANSACTION_ID,SHIPMENT_ID
-- FROM PURCHASE_ORDERS
-- WHERE SUPPLIER_ID=2 AND ORDER_ID=4
-- 
-- 








































