-------to show purchase orders

SELECT DISTINCT PT.TRANSACTION_ID,O.NAME, PT.STATUS, FT.STATUS AS PAYMENT_STATUS, S2.STATUS AS SHIPMENT_STATUS
FROM PRODUCT_TRANSACTIONS PT JOIN ORGANIZATIONS O ON O.ORGANIZATION_ID=PT.COUNTERPARTY_ID
JOIN FINANCIAL_TRANSACTIONS FT ON FT.PRODUCT_TRANSACTION_ID=PT.TRANSACTION_ID
JOIN (
SELECT S.SHIPMENT_ID, S.PRODUCT_TRANSACTION_ID,
CASE 
		WHEN S.ARRIVAL_DATE IS NULL THEN 'PENDING'
		ELSE 'COMPLETED'
END STATUS
FROM SHIPMENTS S
) S2 ON S2.PRODUCT_TRANSACTION_ID=PT.TRANSACTION_ID
WHERE PT.TYPE='PURCHASE_TRANSACTION'
ORDER BY PT.TRANSACTION_ID DESC

--deatils page
SELECT DISTINCT PT.TRANSACTION_ID,PT.PICKUP_DATE,O.NAME, PT.STATUS, S2.STATUS AS SHIPMENT_STATUS
FROM PRODUCT_TRANSACTIONS PT JOIN ORGANIZATIONS O ON O.ORGANIZATION_ID=PT.COUNTERPARTY_ID
WHERE PT.TRANSACTION_ID=6

--FINANCIAL DETAILS OF A PO
SELECT FT.METHOD, PI.ACCOUNT_NUMBER,PI.BANK_NAME, FT.AMOUNT,FT.STATUS
FROM FINANCIAL_TRANSACTIONS FT JOIN PAYMENT_INFO PI ON FT.TO_ACCOUNT=PI.OWNER_ID
WHERE FT.PRODUCT_TRANSACTION_ID=6 AND TYPE= UPPER('PURCHASE_ORDER_PAYMENT')

--SHIPMENT DETAILS OF A PO
SELECT O.NAME, L1.STREET_ADDRESS||', '||L1.CITY||'-'||L1.POSTAL_CODE||','||L1.COUNTRY AS PICK_UP_FROM, S.DEPARTURE_DATE,S.DEPARTURE_TIME,S.VEHICLE_NO,S.CURRENT_LOCATION,S.ARRIVAL_DATE,S.ARRIVAL_TIME,
CASE 
		WHEN S.ARRIVAL_DATE IS NULL THEN 'PENDING'
		ELSE 'COMPLETED'
END STATUS
FROM SHIPMENTS S JOIN ORGANIZATIONS O ON O.ORGANIZATION_ID=S.TRANSPORT_COMPANY_ID
		JOIN LOCATIONS L1 ON S.START_LOCATION=L1.LOCATION_ID
WHERE S.PRODUCT_TRANSACTION_ID=6


--purchase list of a po
SELECT P.PRODUCT_NAME,OP.PRICE/OP.QUANTITY AS PRICE_EACH,OP.QUANTITY
FROM ORDER_PRODUCTS OP JOIN PRODUCTS P ON P.PRODUCT_ID=OP.PRODUCT_ID
WHERE OP.ORDER_ID=6

--
SELECT O.ORGANIZATION_ID,O.NAME
FROM ORGANIZATIONS O
WHERE O.TYPE='SUPPLIER'

SELECT S.SUPPLIER_ID, O.NAME,L2.STREET_ADDRESS||','||L2.CITY||'-'||L2.POSTAL_CODE||','||L2.COUNTRY PICKUP_LOCATION,P.ACCOUNT_NUMBER,P.ACCOUNT_HOLDER,P.BANK_NAME  FROM ORGANIZATIONS O JOIN SUPPLIERS S ON (O.ORGANIZATION_ID=S.SUPPLIER_ID) LEFT OUTER JOIN LOCATIONS L2 ON (O.ORGANIZATION_ID=L2.ORGANIZATION_ID AND (UPPER(L2.TYPE) IN ('DUAL','PICKUP'))) LEFT OUTER JOIN PAYMENT_INFO P ON (S.SUPPLIER_ID=P.OWNER_ID) WHERE S.SUPPLIER_ID=2


--------------

SELECT *
FROM SUPPLY_REQUESTS SR JOIN ORGANIZATIONS O ON O.ORGANIZATION_ID=SR.BRANCH_ID
ORDER BY SR.PLACEMENT_DATE, SR.DEADLINE
where UPPER(O.NAME) LIKE '%BANANI%' OR sr.PLACEMENT_DATE=TO_DATE('BANANI', 'DD-MM-RR')

SELECT *
FROM SUPPLY_REQUEST_PRODUCTS SRP JOIN PRODUCTS P ON P.PRODUCT_ID=SRP.PRODUCT_ID
WHERE SRP.REQUEST_ID =3



SELECT*
FROM CONFIRMED_SUPPLY

SELECT *
        FROM SUPPLY_REQUESTS SR JOIN ORGANIZATIONS O ON O.ORGANIZATION_ID=SR.BRANCH_ID
        WHERE SR.REQUEST_ID= 3

SELECT PT.TRANSACTION_ID, PT.PICKUP_DATE,PT.STATUS
FROM CONFIRMED_SUPPLY CS JOIN SUPPLY_REQUESTS SR ON SR.REQUEST_ID=CS.REQUEST_ID 
		JOIN PRODUCT_TRANSACTIONS PT ON PT.TRANSACTION_ID=CS.SUPPLY_ID
WHERE SR.REQUEST_ID=2



SELECT REQ.PRODUCT_ID,P.PRODUCT_NAME,REQ.QUANTITY_REQUESTED,( REQ.QUANTITY_REQUESTED-NVL(CONFIRM.QUANTITY_DELIVERED, 0) ) AS QUANTITY_LEFT, P.CENTRAL_STOCK
FROM 
(
SELECT SRP.PRODUCT_ID,SRP.QUANTITY AS QUANTITY_REQUESTED
FROM SUPPLY_REQUEST_PRODUCTS SRP
WHERE SRP.REQUEST_ID=4
) REQ LEFT OUTER JOIN
(
SELECT CSP.PRODUCT_ID, SUM(CSP.QUANTITY) AS QUANTITY_DELIVERED
FROM CONFIRMED_SUPPLY_PRODUCTS CSP JOIN CONFIRMED_SUPPLY CS ON CS.SUPPLY_ID=CSP.SUPPLY_ID
WHERE CS.REQUEST_ID=4
GROUP BY CSP.PRODUCT_ID
) CONFIRM ON REQ.PRODUCT_ID=CONFIRM.PRODUCT_ID  
LEFT OUTER JOIN PRODUCTS P ON REQ.PRODUCT_ID=P.PRODUCT_ID

---------------------------
SELECT SUM( REQ.QUANTITY_REQUESTED-NVL(CONFIRM.QUANTITY_DELIVERED, 0) ) 
FROM 
(
SELECT SRP.PRODUCT_ID,SRP.QUANTITY AS QUANTITY_REQUESTED
FROM SUPPLY_REQUEST_PRODUCTS SRP
WHERE SRP.REQUEST_ID=4
) REQ LEFT OUTER JOIN
(
SELECT CSP.PRODUCT_ID, SUM(CSP.QUANTITY) AS QUANTITY_DELIVERED
FROM CONFIRMED_SUPPLY_PRODUCTS CSP JOIN CONFIRMED_SUPPLY CS ON CS.SUPPLY_ID=CSP.SUPPLY_ID
WHERE CS.REQUEST_ID=4
GROUP BY CSP.PRODUCT_ID
) CONFIRM ON REQ.PRODUCT_ID=CONFIRM.PRODUCT_ID  
LEFT OUTER JOIN PRODUCTS P ON REQ.PRODUCT_ID=P.PRODUCT_ID

--------------------
SELECT DISTINCT PT.TRANSACTION_ID,O.NAME, PT.STATUS, FT.STATUS AS PAYMENT_STATUS, S2.STATUS AS SHIPMENT_STATUS
FROM PRODUCT_TRANSACTIONS PT JOIN ORGANIZATIONS O ON O.ORGANIZATION_ID=PT.COUNTERPARTY_ID
JOIN FINANCIAL_TRANSACTIONS FT ON FT.PRODUCT_TRANSACTION_ID=PT.TRANSACTION_ID
JOIN (
SELECT S.SHIPMENT_ID, S.PRODUCT_TRANSACTION_ID,
CASE 
		WHEN S.ARRIVAL_DATE IS NULL THEN 'PENDING'
		ELSE 'COMPLETED'
END STATUS
FROM SHIPMENTS S
) S2 ON S2.PRODUCT_TRANSACTION_ID=PT.TRANSACTION_ID
WHERE FT.TYPE='CLIENT_ORDER_PAYMENT'  
ORDER BY PT.TRANSACTION_ID DESC



----
UPDATE PRODUCT_TRANSACTIONS
SET STATUS='PENDING'
WHERE TRANSACTION_ID=2

DELETE FROM SHIPMENTS WHERE SHIPMENT_ID=4