
--TO GET ALL INFO OF  A SUPPLIER
SELECT S.SUPPLIER_ID,S.SUPPLIER_NAME,S.CITY,S.COUNTRY,S.URL,S.AVG_DELIVERY_TIME,P.ACCOUNT_NUMBER,P.ACCOUNT_HOLDER,P.BANK_NAME,
P.IBAN, L.STREET_ADDRESS,L.POSTAL_CODE,L.CITY AS PICKUP_LOC_CITY,L.COUNTRY AS PICKUP_LOC_COUNTRY,C.PHONE_NO,C.EMAIL
FROM SUPPLIERS S 
		JOIN PAYMENT_INFO P ON S.PAYMENT_INFO_ID=P.ID
		JOIN LOCATIONS L ON L.LOCATION_ID=S.PICKUP_LOCATION_ID
		JOIN (
		SELECT DISTINCT C1.OWNER_ID AS SUPPLIER_ID, C1.VALUE AS PHONE_NO, C2.VALUE AS EMAIL
		FROM CONTACTS C1 JOIN CONTACTS C2 ON (C1.OWNER_ID=C2.OWNER_ID	AND C1.TYPE <> C2.TYPE AND C1.TYPE='PHONE')
		) C ON C.SUPPLIER_ID=S.SUPPLIER_ID 
WHERE S.SUPPLIER_ID=5
ORDER BY S.SUPPLIER_ID
		

--TO GET PRODUCT CATALOGUE
SELECT SP.PRODUCT_ID, P.PRODUCT_NAME,P.CATEGORY,P.PRICE,P.WARRANTY,P.MANUFACTURER,P.CENTRAL_STOCK
FROM SUPPLIER_PRODUCT SP JOIN PRODUCTS P ON SP.PRODUCT_ID=P.PRODUCT_ID
WHERE SP.SUPPLIER_ID=4

