
--TO GET ALL INFO OF  A SUPPLIER
SELECT S.SUPPLIER_ID,S.SUPPLIER_NAME,S.CITY,S.COUNTRY,S.URL,S.AVG_DELIVERY_TIME,P.ACCOUNT_NUMBER,P.ACCOUNT_HOLDER,P.BANK_NAME,
P.IBAN, L.STREET_ADDRESS,L.POSTAL_CODE,L.CITY AS PICKUP_LOC_CITY,L.COUNTRY AS PICKUP_LOC_COUNTRY,C.PHONE_NO,C.EMAIL
FROM SUPPLIERS S 
		JOIN PAYMENT_INFO P ON S.PAYMENT_INFO_ID=P.ID
		JOIN LOCATIONS L ON L.LOCATION_ID=S.PICKUP_LOCATION_ID
		JOIN (
		SELECT DISTINCT C1.OWNER_ID AS SUPPLIER_ID, C1.VALUE AS PHONE_NO, C2.VALUE AS EMAIL
		FROM CONTACTS C1 JOIN CONTACTS C2 ON (C1.OWNER_ID=C2.OWNER_ID	AND C1.TYPE <> C2.TYPE AND C1.TYPE='PHONE')
		) C ON C.SUPPLIER_ID=S.SUPPLIER_ID 
WHERE S.SUPPLIER_ID=5
ORDER BY S.SUPPLIER_ID
		

--TO GET PRODUCT CATALOGUE
SELECT SP.PRODUCT_ID, P.PRODUCT_NAME,P.CATEGORY,P.PRICE,P.WARRANTY,P.MANUFACTURER,P.CENTRAL_STOCK
FROM SUPPLIER_PRODUCT SP JOIN PRODUCTS P ON SP.PRODUCT_ID=P.PRODUCT_ID
WHERE SP.SUPPLIER_ID=4;

--TO GET THE LIST OF PURHCASE ORDERS TO A SUPPLIER
SELECT ORDER_ID, PLACEMENT_DATE,PICKUP_DATE
FROM PURCHASE_ORDERS
WHERE SUPPLIER_ID=2
ORDER BY ORDER_ID;


--TO GET THE DETAILS (FINANCIAL AND SHIPMENT RELATED INFO) OF A PURCHASE ORDER
SELECT *
FROM (
	SELECT ORDER_ID,PLACEMENT_DATE,PICKUP_DATE,TRANSACTION_ID,SHIPMENT_ID
	FROM PURCHASE_ORDERS
	WHERE SUPPLIER_ID=2 AND ORDER_ID=4
) PO 
	JOIN 
	(
	SELECT FT.TRANSACTION_ID, FT.METHOD, PI1.ACCOUNT_HOLDER AS SENT_FROM_ACOOUNT, PI2.ACCOUNT_HOLDER AS RECEIVED_TO_ACCOUNT,FT.STATUS, (FT.AMOUNT || ' ' || UPPER(FT.CURRENCY)) AS AMOUNT, FT.PLACEMENT_DATE AS PAYMENT_DATE
	FROM FINANCIAL_TRANSACTIONS FT 
		JOIN PAYMENT_INFO PI1 ON (FT.FROM_ACCOUNT=PI1.ID)
		JOIN PAYMENT_INFO PI2 ON (FT.TO_ACCOUNT=PI2.ID)
	--WHERE FT.TRANSACTION_ID=4
	) F USING(TRANSACTION_ID)--ON F.TRANSACTION_ID=PO.TRANSACTION_ID
	JOIN
	(
	SELECT S.SHIPMENT_ID,TC.NAME AS PICKED_UP_BY, (L1.STREET_ADDRESS||', '||L1.CITY|| ', '||L1.COUNTRY) AS PICKED_UP_FROM,(S.DEPARTURE_DATE) AS PICKED_UP_ON,(S.DEPARTURE_TIME) AS PICKED_UP_AT,(L2.STREET_ADDRESS||', '||L2.CITY|| ', '||L2.COUNTRY) AS RECEIVED_AT, (S.ARRIVAL_DATE) AS RECEIVED_ON, S.ARRIVAL_TIME AS RECEIVED_AT_TIME, S.VEHICLE_NO AS VEHICLE_USED, S.CURRENT_LOCATION
	FROM SHIPMENTS S 
		JOIN TRANSPORT_COMPANIES TC ON TC.COMPANY_ID=S.TRANSPORT_COMPANY_ID
		JOIN LOCATIONS L1 ON S.START_LOCATION=L1.LOCATION_ID
		JOIN LOCATIONS L2 ON S.DESTINATION=L2.LOCATION_ID
	) SI USING(SHIPMENT_ID)--ON SI.SHIPMENT_ID=PO.SHIPMENT_ID
	

--TO GET THE PURCHASED PRODUCT LIST IN A PURCHASE ORDER
SELECT P.PRODUCT_NAME,POP.QUANTITY, P.PRICE,(POP.QUANTITY*P.PRICE) AS TOTAL_DUE
FROM PURCHASE_ORDER_PRODUCTS POP 
	JOIN PRODUCTS P ON POP.PRODUCT_ID=P.PRODUCT_ID
WHERE POP.ORDER_ID=1



-- SELECT S.SHIPMENT_ID,TC.NAME AS PICKED_UP_BY, (L1.STREET_ADDRESS||', '||L1.CITY|| ', '||L1.COUNTRY) AS PICKED_UP_FROM,(S.DEPARTURE_DATE) AS PICKED_UP_ON,(S.DEPARTURE_TIME) AS PICKED_UP_AT,(L2.STREET_ADDRESS||', '||L2.CITY|| ', '||L2.COUNTRY) AS RECEIVED_AT, (S.ARRIVAL_DATE) AS RECEIVED_ON, S.ARRIVAL_TIME AS RECEIVED_AT_TIME, S.VEHICLE_NO AS VEHICLE_USED, S.CURRENT_LOCATION
-- FROM SHIPMENTS S 
-- 	JOIN TRANSPORT_COMPANIES TC ON TC.COMPANY_ID=S.TRANSPORT_COMPANY_ID
-- 	JOIN LOCATIONS L1 ON S.START_LOCATION=L1.LOCATION_ID
-- 	JOIN LOCATIONS L2 ON S.DESTINATION=L2.LOCATION_ID



--PRODUCTS
--product search
SELECT * FROM PRODUCTS P2 WHERE P2.PRODUCT_ID IN
(SELECT DISTINCT P1.PRODUCT_ID FROM PRODUCTS P1 
LEFT OUTER JOIN PRODUCT_FEATURES PF ON(P1.PRODUCT_ID=PF.PRODUCT_ID) 
LEFT OUTER JOIN FEATURE_NAMES FN ON (PF.FEATURE_ID=FN.FEATURE_ID)
WHERE UPPER(P1.PRODUCT_NAME) LIKE UPPER('%REFRESH%') OR UPPER(P1.CATEGORY) LIKE UPPER('%REFRESH%') OR UPPER(P1.MANUFACTURER_ID) LIKE UPPER('%REFRESH%')
OR UPPER(PF.VALUE) LIKE UPPER('%REFRESH%') OR UPPER(FN.FEATURE_NAME) LIKE UPPER('%REFRESH%')
)
ORDER BY P2.PRODUCT_ID; 

--acquire product details


SELECT * FROM PRODUCT_FEATURES PF JOIN FEATURE_NAMES FN ON (PF.FEATURE_ID=FN.FEATURE_ID) WHERE PF.PRODUCT_ID=2;

SELECT SP.SUPPLIER_ID SUPPLIER_ID, O.NAME SUPPLIER_NAME,SP.WHOLESALE_PRICE OFFERING_PRICE, S.AVG_DELIVERY_TIME AVG_DELIVERY_TIME FROM  SUPPLIER_PRODUCT SP  
JOIN ORGANIZATIONS O ON (SP.SUPPLIER_ID=O.ORGANIZATION_ID)
JOIN SUPPLIERS S ON (O.ORGANIZATION_ID=S.SUPPLIER_ID) WHERE SP.PRODUCT_ID=2;


--BRANCHES

SELECT B.BRANCH_ID, O.NAME, B.MANAGER, STREET_ADDRESS||', '||CITY||'-'||POSTAL_CODE ADDRESS FROM
ORGANIZATIONS O JOIN BRANCHES B ON (O.ORGANIZATION_ID=B.BRANCH_ID)
LEFT OUTER JOIN LOCATIONS L ON (O.ADDRESS=L.LOCATION_ID)
ORDER BY O.ORGANIZATION_ID;



SELECT B.BRANCH_ID, O.NAME, B.MANAGER,
STREET_ADDRESS||', '||CITY||'-'||POSTAL_CODE ADDRESS,
B.SQUARE_FOOTAGE,B.AVG_SHIPPING_DURATION,
P.ACCOUNT_NUMBER,P.ACCOUNT_HOLDER,P.BANK_NAME,P.IBAN FROM
ORGANIZATIONS O JOIN BRANCHES B ON (O.ORGANIZATION_ID=B.BRANCH_ID)
LEFT OUTER JOIN LOCATIONS L ON (O.ADDRESS=L.LOCATION_ID) 
LEFT OUTER JOIN PAYMENT_INFO P ON (B.BRANCH_ID=P.OWNER_ID)
WHERE B.BRANCH_ID=13
ORDER BY O.ORGANIZATION_ID;

--ACTUALLY, i THINK ORGANIZATIONS AND BRANCH LEFT OUTER JOIN KORLE BHALO HOY, THAT DEPENDS ON NOTUN BRANCH KAMNE CREATE HOY

SELECT * FROM CONTACTS WHERE OWNER_ID=17 AND UPPER(TYPE)='PHONE_NUMBER';

SELECT O.NAME FROM ORGANIZATIONS O JOIN BRANCHES B ON (O.ORGANIZATION_ID=B.BRANCH_ID) WHERE B.BRANCH_ID=13;


SELECT * FROM BRANCH_INCOME_STATEMENT WHERE BRANCH_ID=16;

SELECT * 
FROM BRANCH_INCOME_STATEMENT where  EXTRACT(MONTH FROM START_DATE)=12  AND EXTRACT(YEAR FROM START_DATE)=2023 AND BRANCH_ID=13;

SELECT * 
FROM BRANCH_INCOME_STATEMENT where EXTRACT(YEAR FROM START_DATE)=2023 AND BRANCH_ID=13;


-- SELECT FT.TRANSACTION_ID, FT.METHOD, PI1.ACCOUNT_HOLDER AS SENT_FROM_ACOOUNT, PI2.ACCOUNT_HOLDER AS RECEIVED_TO_ACCOUNT,FT.STATUS, (FT.AMOUNT || ' ' || UPPER(FT.CURRENCY)) AS AMOUNT
-- FROM FINANCIAL_TRANSACTIONS FT 
-- 	JOIN PAYMENT_INFO PI1 ON (FT.FROM_ACCOUNT=PI1.ID)
-- 	JOIN PAYMENT_INFO PI2 ON (FT.TO_ACCOUNT=PI2.ID)
-- WHERE FT.TRANSACTION_ID=4
-- 
-- 
-- SELECT TRANSACTION_ID,SHIPMENT_ID
-- FROM PURCHASE_ORDERS
-- WHERE SUPPLIER_ID=2 AND ORDER_ID=4
-- 
-- 

--CLIENT_COMPANIES

SELECT C.CLIENT_ID, O.NAME, O.URL, STREET_ADDRESS||', '||CITY||'-'||POSTAL_CODE ADDRESS FROM
ORGANIZATIONS O JOIN CLIENT_COMPANIES C ON (O.ORGANIZATION_ID=C.CLIENT_ID)
LEFT OUTER JOIN LOCATIONS L ON (O.ADDRESS=L.LOCATION_ID)
ORDER BY O.ORGANIZATION_ID;

SELECT C.CLIENT_ID, O.NAME, O.URL, STREET_ADDRESS||', '||CITY||'-'||POSTAL_CODE ADDRESS FROM
ORGANIZATIONS O JOIN CLIENT_COMPANIES C ON (O.ORGANIZATION_ID=C.CLIENT_ID)
LEFT OUTER JOIN LOCATIONS L ON (O.ADDRESS=L.LOCATION_ID)
WHERE UPPER(NAME) LIKE :searchPattern OR UPPER(STREET_ADDRESS) LIKE :searchPattern OR 
UPPER(POSTAL_CODE) LIKE :searchPattern 
OR UPPER(CITY) LIKE :searchPattern
OR UPPER(COUNTRY) LIKE :searchPattern OR UPPER(C.TYPE) LIKE :searchPattern
OR UPPER(URL) LIKE :searchPattern
OR UPPER(C.TYPE) LIKE :searchPattern
ORDER BY O.ORGANIZATION_ID



SELECT C.CLIENT_ID, O.NAME, C.TYPE, O.URL,
STREET_ADDRESS||', '||CITY||'-'||POSTAL_CODE ADDRESS,
P.ACCOUNT_NUMBER,P.ACCOUNT_HOLDER,P.BANK_NAME,P.IBAN FROM
ORGANIZATIONS O JOIN CLIENT_COMPANIES C ON (O.ORGANIZATION_ID=C.CLIENT_ID)
LEFT OUTER JOIN LOCATIONS L ON (O.ADDRESS=L.LOCATION_ID) 
LEFT OUTER JOIN PAYMENT_INFO P ON (C.CLIENT_ID=P.OWNER_ID)
WHERE C.CLIENT_ID=22
ORDER BY O.ORGANIZATION_ID;

--TRANPSPORT COMPANIES

SELECT T.COMPANY_ID, O.NAME, O.URL, STREET_ADDRESS||', '||CITY||'-'||POSTAL_CODE ADDRESS,T.CAPACITY FROM
ORGANIZATIONS O JOIN TRANSPORT_COMPANIES T ON (O.ORGANIZATION_ID=T.COMPANY_ID)
LEFT OUTER JOIN LOCATIONS L ON (O.ADDRESS=L.LOCATION_ID)
ORDER BY O.ORGANIZATION_ID;

SELECT T.COMPANY_ID, O.NAME, O.URL, STREET_ADDRESS||', '||CITY||'-'||POSTAL_CODE ADDRESS,T.CAPACITY FROM
ORGANIZATIONS O JOIN TRANSPORT_COMPANIES T ON (O.ORGANIZATION_ID=T.COMPANY_ID)
LEFT OUTER JOIN LOCATIONS L ON (O.ADDRESS=L.LOCATION_ID)
WHERE UPPER(O.NAME) LIKE :searchPattern OR UPPER(STREET_ADDRESS) LIKE :searchPattern OR UPPER(CITY) LIKE :searchPattern
OR UPPER(POSTAL_CODE) LIKE :searchPattern
OR UPPER(COUNTRY) LIKE :searchPattern
OR UPPER(CITY) LIKE :searchPattern
OR UPPER(URL) LIKE :searchPattern
ORDER BY O.ORGANIZATION_ID;

SELECT S.SUPPLIER_ID, O.NAME, O.URL,S.AVG_DELIVERY_TIME, L1.STREET_ADDRESS||', '||L1.CITY||'-'||L1.POSTAL_CODE||','||L1.COUNTRY ADDRESS,L2.STREET_ADDRESS||', '||L2.CITY||'-'||L2.POSTAL_CODE||','||L2.COUNTRY PICKUP_LOCATION  FROM
                ORGANIZATIONS O JOIN SUPPLIERS S ON (O.ORGANIZATION_ID=S.SUPPLIER_ID)
                LEFT OUTER JOIN LOCATIONS L1 ON (O.ORGANIZATION_ID=L1.ORGANIZATION_ID AND (UPPER(L1.TYPE) IN ('DUAL','ADDRESS')))
                LEFT OUTER JOIN LOCATIONS L2 ON (O.ORGANIZATION_ID=L2.ORGANIZATION_ID AND (UPPER(L2.TYPE) IN ('DUAL','PICKUP')))
                ORDER BY O.ORGANIZATION_ID

SELECT S.SUPPLIER_ID, O.NAME, O.URL,S.AVG_DELIVERY_TIME, L1.STREET_ADDRESS||', '||L1.CITY||'-'||L1.POSTAL_CODE||','||L1.COUNTRY ADDRESS,L2.STREET_ADDRESS||', '||L2.CITY||'-'||L2.POSTAL_CODE||','||L2.COUNTRY PICKUP_LOCATION  FROM
ORGANIZATIONS O JOIN SUPPLIERS S ON (O.ORGANIZATION_ID=S.SUPPLIER_ID)
LEFT OUTER JOIN LOCATIONS L1 ON (O.ORGANIZATION_ID=L1.ORGANIZATION_ID AND (UPPER(L1.TYPE) IN ('DUAL','ADDRESS')))
LEFT OUTER JOIN LOCATIONS L2 ON (O.ORGANIZATION_ID=L2.ORGANIZATION_ID AND (UPPER(L2.TYPE) IN ('DUAL','PICKUP')))
WHERE UPPER(NAME) LIKE :searchPattern OR UPPER(l1.STREET_ADDRESS) LIKE :searchPattern OR 
UPPER(L1.POSTAL_CODE) LIKE :searchPattern 
OR UPPER(L1.CITY) LIKE :searchPattern
OR UPPER(L1.COUNTRY) LIKE :searchPattern
OR UPPER(l2.STREET_ADDRESS) LIKE :searchPattern OR 
UPPER(L2.POSTAL_CODE) LIKE :searchPattern 
OR UPPER(L2.CITY) LIKE :searchPattern
OR UPPER(L2.COUNTRY) LIKE :searchPattern
OR UPPER(URL) LIKE :searchPattern
ORDER BY O.ORGANIZATION_ID

SELECT S.SUPPLIER_ID, O.NAME, O.URL,S.AVG_DELIVERY_TIME, L1.STREET_ADDRESS||', '||L1.CITY||'-'||L1.POSTAL_CODE||','||L1.COUNTRY ADDRESS,L2.STREET_ADDRESS||', '||L2.CITY||'-'||L2.POSTAL_CODE||','||L2.COUNTRY PICKUP_LOCATION,P.ACCOUNT_NUMBER,P.ACCOUNT_HOLDER,P.BANK_NAME,P.IBAN  FROM
ORGANIZATIONS O JOIN SUPPLIERS S ON (O.ORGANIZATION_ID=S.SUPPLIER_ID)
LEFT OUTER JOIN LOCATIONS L1 ON (O.ORGANIZATION_ID=L1.ORGANIZATION_ID AND (UPPER(L1.TYPE) IN ('DUAL','ADDRESS')))
LEFT OUTER JOIN LOCATIONS L2 ON (O.ORGANIZATION_ID=L2.ORGANIZATION_ID AND (UPPER(L2.TYPE) IN ('DUAL','PICKUP')))
LEFT OUTER JOIN PAYMENT_INFO P ON (S.SUPPLIER_ID=P.OWNER_ID) WHERE S.SUPPLIER_ID=2;

















