CREATE SEQUENCE LOCATION_ID_SEQ
INCREMENT BY 1
START WITH 34;


CREATE SEQUENCE ORGANIZATION_ID_SEQ
INCREMENT BY 1
START WITH 29;

CREATE SEQUENCE PAYMENTINFO_ID_SEQ
INCREMENT BY 1
START WITH 29;

CREATE SEQUENCE PRODUCT_ID_SEQ
INCREMENT BY 1
START WITH 46;

