-- -- Supplier 2
-- Supplier 2
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 2, 134500);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 4, 213200);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 6, 235700);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 8, 128200);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 10, 111800);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 12, 51500);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 14, 59200);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 16, 127200);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 18, 239500);

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE)
VALUES (2, 20, 100500);
-- 
-- Supplier 3
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 1, 109000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 3, 111000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 5, 75000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 7, 124000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 9, 154000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 11, 84000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 13, 279000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 15, 93000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 17, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 19, 170000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 21, 25000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 23, 5000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 25, 25000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 27, 15000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 29, 35000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 31, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 33, 9000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 35, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 37, 10000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (3, 39, 14000);

-- -- Supplier 4
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 2, 135000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 4, 212000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 6, 237000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 8, 126000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 10, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 12, 51500);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 14, 59000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 16, 127000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 18, 240000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (4, 20, 100000);

-- Supplier 5
-- Supplier 5
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 1, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 3, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 5, 75000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 7, 125000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 9, 154000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 11, 85000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 13, 280000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 15, 93000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 17, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 19, 171000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 21, 25000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 23, 5000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 25, 28000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 27, 16000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 29, 35000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 31, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 33, 9000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 35, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 37, 10000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 39, 14000);

-- 
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 2, 136000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 4, 212000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 6, 237000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 8, 126000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 10, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 12, 51500);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 14, 59000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 16, 127000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 18, 240000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 20, 100000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 22, 8500);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 24, 48000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 26, 12000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 28, 28000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 30, 16000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 32, 35000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 34, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 36, 9000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 38, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 40, 10000);
-- 
-- -- Supplier 7
-- Supplier 7
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 21, 25000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 23, 8500);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 25, 48000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 27, 12000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 29, 28000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 31, 16000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 33, 35000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 35, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 37, 9000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 39, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 41, 10000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 43, 14000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 45, 8000);

-- 
-- -- Supplier 8
-- Supplier 8
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 1, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 3, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 5, 75000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 7, 125000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 9, 154000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 11, 85000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 13, 280000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 15, 93000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 17, 110000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 19, 171000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 21, 25000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 23, 5000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 25, 28000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 27, 16000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 29, 35000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 31, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 33, 9000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 35, 18000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 37, 10000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 39, 14000);


-- Supplier 5
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 42, 11000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (5, 44, 18000);

-- Supplier 6
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 42, 17000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (6, 44, 25000);

-- Supplier 7
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 42, 35000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (7, 44, 18000);

-- Supplier 8
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 42, 9000);
INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID, WHOLESALE_PRICE) VALUES (8, 44, 18000);
