CREATE SEQUENCE LOCATION_ID_SEQ
INCREMENT BY 1
START WITH 34;


CREATE SEQUENCE ORGANIZATION_ID_SEQ
INCREMENT BY 1
START WITH 29;

CREATE SEQUENCE PAYMENTINFO_ID_SEQ
INCREMENT BY 1
START WITH 29;

CREATE SEQUENCE PRODUCT_ID_SEQ
INCREMENT BY 1
START WITH 46;

--new sequences march 5

CREATE SEQUENCE SUPPLYREQ_ID_SEQ
INCREMENT BY 1
START WITH 6;

CREATE SEQUENCE PTRANSACTION_ID_SEQ
INCREMENT BY 1
START WITH 19;

CREATE SEQUENCE FTRANSACTION_ID_SEQ
INCREMENT BY 1
START WITH 29;

CREATE SEQUENCE SHIPMENT_ID_SEQ
INCREMENT BY 1
START WITH 19;