--SUPPLY_REQUESTS

--SR 1
-- Insert into SUPPLY_REQUESTS
INSERT INTO SUPPLY_REQUESTS (REQUEST_ID, PLACEMENT_DATE, DEADLINE, BRANCH_ID,STATUS)
VALUES (1, TO_DATE('25-FEB-23', 'DD-MON-RR'), TO_DATE('15-MAR-23', 'DD-MON-RR'), 12, 'COMPLETED');
-- Insert into SUPPLY_REQUEST_PRODUCTS
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (1, 1, 5);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (1, 2, 5);

--SR 2
-- Insert into SUPPLY_REQUESTS
INSERT INTO SUPPLY_REQUESTS (REQUEST_ID, PLACEMENT_DATE, DEADLINE, BRANCH_ID, STATUS)
VALUES (2, TO_DATE('25-FEB-22', 'DD-MON-RR'), TO_DATE('15-MAR-22', 'DD-MON-RR'), 13, 'COMPLETED');
-- Insert into SUPPLY_REQUEST_PRODUCTS
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (2, 3, 5);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (2, 12, 13);

--SR 3
-- Insert into SUPPLY_REQUESTS
INSERT INTO SUPPLY_REQUESTS (REQUEST_ID, PLACEMENT_DATE, DEADLINE, BRANCH_ID,STATUS)
VALUES (3, TO_DATE('26-FEB-24', 'DD-MON-RR'), TO_DATE('25-MAR-24', 'DD-MON-RR'), 13, 'PENDING');
-- Insert into SUPPLY_REQUEST_PRODUCTS
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (3, 3, 15);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (3, 27, 10);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (3, 24, 10);

--SR 4
-- Insert into SUPPLY_REQUESTS
INSERT INTO SUPPLY_REQUESTS (REQUEST_ID, PLACEMENT_DATE, DEADLINE, BRANCH_ID, STATUS)
VALUES (4, TO_DATE('24-FEB-24', 'DD-MON-RR'), TO_DATE('17-MAR-24', 'DD-MON-RR'), 14, 'PENDING');
-- Insert into SUPPLY_REQUEST_PRODUCTS
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (4, 34, 15);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (4, 37, 20);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (4, 4, 5);

--SR 5
-- Insert into SUPPLY_REQUESTS
INSERT INTO SUPPLY_REQUESTS (REQUEST_ID, PLACEMENT_DATE, DEADLINE, BRANCH_ID,STATUS)
VALUES (5, TO_DATE('1-MAR-24', 'DD-MON-RR'), TO_DATE('27-MAR-24', 'DD-MON-RR'), 16, 'PENDING');
-- Insert into SUPPLY_REQUEST_PRODUCTS
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (5, 16, 10);

INSERT INTO SUPPLY_REQUESTS (REQUEST_ID, PLACEMENT_DATE, DEADLINE, BRANCH_ID,STATUS)
VALUES (6, TO_DATE('3-MAR-24', 'DD-MON-RR'), TO_DATE('30-MAR-24', 'DD-MON-RR'), 16, 'PENDING');
-- Insert into SUPPLY_REQUEST_PRODUCTS
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (6, 20, 10);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (6, 10, 15);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (6, 13, 11);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (6, 16, 5);

INSERT INTO SUPPLY_REQUESTS (REQUEST_ID, PLACEMENT_DATE, DEADLINE, BRANCH_ID,STATUS)
VALUES (7, TO_DATE('7-MAR-24', 'DD-MON-RR'), TO_DATE('1-APR-24', 'DD-MON-RR'), 12, 'PENDING');
-- Insert into SUPPLY_REQUEST_PRODUCTS
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (7, 1, 10);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (7, 5, 11);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (7, 7, 13);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (7, 20, 14);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (7, 35, 16);

INSERT INTO SUPPLY_REQUESTS (REQUEST_ID, PLACEMENT_DATE, DEADLINE, BRANCH_ID,STATUS)
VALUES (8, TO_DATE('8-MAR-24', 'DD-MON-RR'), TO_DATE('29-MAR-24', 'DD-MON-RR'), 13, 'PENDING');
-- Insert into SUPPLY_REQUEST_PRODUCTS
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (8, 18, 12);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (8, 20, 5);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (8, 12, 10);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (8, 15, 13);
INSERT INTO SUPPLY_REQUEST_PRODUCTS (REQUEST_ID, PRODUCT_ID, QUANTITY)
VALUES (8, 22, 12);














































