/*INSERT ALL
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'Processor', 'Intel Core i5')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'RAM', '8GB')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'Storage', '256GB SSD')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'Screen Size', '13.3 inches')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'Graphics Card', 'Intel UHD Graphics 620')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'Operating System', 'Windows 10 Home')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'Weight', '1.23')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'Battery Life', '10')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (1, 'Price', '111000')

-- Features for HP Spectre x360
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'Processor', 'Intel Core i7')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'RAM', '16GB')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'Storage', '1TB SSD')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'Screen Size', '15.6 inches')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'Graphics Card', 'NVIDIA GeForce MX330')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'Operating System', 'Windows 11')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'Weight', '1.34')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'Battery Life', '12')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (2, 'Price', '136000')

-- Features for MacBook Air
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'Processor', 'Apple M1 Chip')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'RAM', '8GB')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'Storage', '512GB SSD')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'Screen Size', '13.3 inches')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'Graphics Card', 'Apple M1 (8-core GPU)')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'Operating System', 'macOS Monterey')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'Weight', '1.29')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'Battery Life', '15')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (3, 'Price', '111000')

-- Features for Lenovo ThinkPad X1
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'Processor', 'Intel Core i9')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'RAM', '32GB')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'Storage', '1TB NVMe')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'Screen Size', '14 inches')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'Graphics Card', 'NVIDIA GeForce GTX 1650')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'Operating System', 'Windows 10 Pro')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'Weight', '1.35')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'Battery Life', '13')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (4, 'Price', '212500')

-- Features for Acer Swift 3
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'Processor', 'AMD Ryzen 5')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'RAM', '16GB')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'Storage', '512GB SSD')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'Screen Size', '14 inches')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'Graphics Card', 'AMD Radeon Graphics')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'Operating System', 'Windows 10 Home')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'Weight', '1.2')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'Battery Life', '8')
INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (5, 'Price', '76500')

SELECT * FROM dual;*/

/*INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'Processor', 'AMD Ryzen 9')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'RAM', '32GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'Storage', '1TB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'Screen Size', '15.6 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'Graphics Card', 'NVIDIA GeForce RTX 3080')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'Operating System', 'Windows 10 Pro')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'Weight', '2.3')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'Battery Life', NULL)
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (6, 'Price', '238000')
    
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'Processor', 'Intel Core i5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'RAM', '8GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'Storage', '256GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'Screen Size', '13.5 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'Graphics Card', 'Intel Iris Xe Graphics')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'Weight', '1.25')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'Battery Life', '10.5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (7, 'Price', '127000')
    
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'Processor', 'Intel Core i7')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'RAM', '16GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'Storage', '1TB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'Screen Size', '17 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'Graphics Card', 'Intel Iris Xe Graphics')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'Weight', '1.35')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'Battery Life', '17')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (8, 'Price', '127500')
    
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'Processor', 'Intel Core i7')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'RAM', '16GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'Storage', '512GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'Screen Size', '15.6 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'Graphics Card', 'NVIDIA GeForce RTX 3070')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'Weight', '2.1')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'Battery Life', '6')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (9, 'Price', '152000')
    
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'Processor', 'Intel Core i7')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'RAM', '16GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'Storage', '1TB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'Screen Size', '14 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'Graphics Card', 'Intel Iris Plus Graphics')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'Weight', '1.35')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'Battery Life', '10')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (10, 'Price', '111000')
SELECT * FROM dual;*/

-- Features for HP Envy x360
/*INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'Processor', 'AMD Ryzen 5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'RAM', '8GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'Storage', '256GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'Screen Size', '13.3 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'Graphics Card', 'AMD Radeon Graphics')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'Weight', '2.3')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'Battery Life', '8')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (11, 'Price', '85000')
SELECT * FROM dual;

-- Features for Dell Inspiron 14
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'Processor', 'Intel Core i5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'RAM', '8GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'Storage', '256GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'Screen Size', '14 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'Graphics Card', 'Intel UHD Graphics 620')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'Weight', '1.66')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'Battery Life', '5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (12, 'Price', '51000')
SELECT * FROM dual;

-- Features for MSI GS66 Stealth
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'Processor', 'Intel Core i7')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'RAM', '32GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'Storage', '1TB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'Screen Size', '15.6 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'Graphics Card', 'NVIDIA GeForce RTX 3080')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'Operating System', 'Windows 10 Pro')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'Weight', '2.1')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'Battery Life', '6')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (13, 'Price', '281000')
SELECT * FROM dual;

-- Features for ASUS VivoBook S
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'Processor', 'Intel Core i5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'RAM', '8GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'Storage', '512GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'Screen Size', '15.6 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'Graphics Card', 'Intel UHD Graphics 620')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'Weight', '3.97')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'Battery Life', '5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (14, 'Price', '59500')
SELECT * FROM dual;

-- Features for Lenovo Legion 5
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'Processor', 'AMD Ryzen 7')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'RAM', '16GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'Storage', '512GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'Screen Size', '15.6 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'Graphics Card', 'NVIDIA GeForce GTX 1660 Ti')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'Weight', '5.41')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'Battery Life', '8')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (15, 'Price', '93100')
SELECT * FROM dual; */

-- Features for Acer Predator Helios 300
/*INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'Processor', 'Intel Core i7')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'RAM', '16GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'Storage', '512GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'Screen Size', '15.6 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'Graphics Card', 'NVIDIA GeForce RTX 3060')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'Weight', '5.07')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'Battery Life', '6')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (16, 'Price', '127500')
SELECT * FROM dual;

-- Features for Dell Latitude 14
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'Processor', 'Intel Core i5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'RAM', '8GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'Storage', '256GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'Screen Size', '14 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'Graphics Card', 'Intel UHD Graphics 620')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'Operating System', 'Windows 10 Pro')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'Weight', '1.67')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'Battery Life', '8')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (17, 'Price', '110000')
SELECT * FROM dual;

-- Features for Apple MacBook Pro 16
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'Processor', 'Intel Core i9')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'RAM', '32GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'Storage', '1TB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'Screen Size', '16 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'Graphics Card', 'AMD Radeon Pro 5500M')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'Operating System', 'macOS Big Sur')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'Weight', '4.3')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'Battery Life', '11')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (18, 'Price', '240000')
SELECT * FROM dual;

-- Features for HP Omen 15
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'Processor', 'Intel Core i7')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'RAM', '16GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'Storage', '512GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'Screen Size', '15.6 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'Graphics Card', 'NVIDIA GeForce RTX 3070')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'Weight', '5.43')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'Battery Life', '6')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (19, 'Price', '170000')
SELECT * FROM dual;

-- Features for ASUS TUF Gaming A15
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'Processor', 'AMD Ryzen 5')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'RAM', '16GB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'Storage', '512GB SSD')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'Screen Size', '15.6 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'Graphics Card', 'NVIDIA GeForce GTX 1660 Ti')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'Operating System', 'Windows 10 Home')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'Weight', '2.3')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'Battery Life', '8')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (20, 'Price', '100000')
SELECT * FROM dual;*/

--monitors

-- Features for Dell Ultrasharp U2419H
/*INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (21, 'Display Size', '24 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (21, 'Resolution', '1920 x 1080')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (21, 'Refresh Rate', '60Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (21, 'Panel Type', 'IPS')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (21, 'Response Time', '5ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (21, 'Price', '25000')
SELECT * FROM dual;

-- Features for HP Pavilion 22cwa
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (22, 'Display Size', '21.5 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (22, 'Resolution', '1920 x 1080')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (22, 'Refresh Rate', '60Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (22, 'Panel Type', 'IPS')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (22, 'Response Time', '7ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (22, 'Price', '8500')
SELECT * FROM dual;

-- Features for LG 27GL83A-B
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (23, 'Display Size', '27 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (23, 'Resolution', '2560 x 1440')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (23, 'Refresh Rate', '144Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (23, 'Panel Type', 'IPS')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (23, 'Response Time', '1ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (23, 'Price', '48000')
SELECT * FROM dual;

-- Features for Acer R240HY
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (24, 'Display Size', '23.8 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (24, 'Resolution', '1920 x 1080')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (24, 'Refresh Rate', '60Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (24, 'Panel Type', 'IPS')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (24, 'Response Time', '4ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (24, 'Price', '12000')
SELECT * FROM dual;

-- Features for ASUS VG279Q
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (25, 'Display Size', '27 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (25, 'Resolution', '1920 x 1080')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (25, 'Refresh Rate', '144Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (25, 'Panel Type', 'IPS')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (25, 'Response Time', '1ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (25, 'Price', '28000')
SELECT * FROM dual;*/

-- Features for Samsung Odyssey G9
/*INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (26, 'Display Size', '49 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (26, 'Resolution', '5120 x 1440')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (26, 'Refresh Rate', '240Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (26, 'Panel Type', 'QLED')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (26, 'Response Time', '1ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (26, 'Price', '150000')
SELECT * FROM dual;

-- Features for ViewSonic XG2402
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (27, 'Display Size', '24 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (27, 'Resolution', '1920 x 1080')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (27, 'Refresh Rate', '144Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (27, 'Panel Type', 'TN')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (27, 'Response Time', '1ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (27, 'Price', '16000')
SELECT * FROM dual;

-- Features for BenQ EX2780Q
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (28, 'Display Size', '27 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (28, 'Resolution', '2560 x 1440')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (28, 'Refresh Rate', '144Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (28, 'Panel Type', 'IPS')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (28, 'Response Time', '5ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (28, 'Price', '35000')
SELECT * FROM dual;

-- Features for Dell S2719DGF
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (29, 'Display Size', '27 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (29, 'Resolution', '2560 x 1440')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (29, 'Refresh Rate', '155Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (29, 'Panel Type', 'TN')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (29, 'Response Time', '1ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (29, 'Price', '42000')
SELECT * FROM dual;

-- Features for HP EliteDisplay E243
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (30, 'Display Size', '23.8 inches')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (30, 'Resolution', '1920 x 1080')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (30, 'Refresh Rate', '60Hz')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (30, 'Panel Type', 'IPS')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (30, 'Response Time', '5ms')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (30, 'Price', '18000')
SELECT * FROM dual;*/

--keyboards

-- Features for Logitech G Pro X Mechanical Gaming Keyboard
/*INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (31, 'Switch Type', 'GX Blue')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (31, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (31, 'Key Rollover', 'N-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (31, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (31, 'Price', '8999')
SELECT * FROM dual;

-- Features for Corsair K95 RGB Platinum XT Mechanical Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (32, 'Switch Type', 'Cherry MX Speed')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (32, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (32, 'Key Rollover', 'N-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (32, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (32, 'Price', '17999')
SELECT * FROM dual;

-- Features for Razer BlackWidow Elite Mechanical Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (33, 'Switch Type', 'Razer Green')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (33, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (33, 'Key Rollover', '10-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (33, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (33, 'Price', '11999')
SELECT * FROM dual;

-- Features for SteelSeries Apex Pro Mechanical Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (34, 'Switch Type', 'OmniPoint Adjustable')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (34, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (34, 'Key Rollover', 'N-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (34, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (34, 'Price', '15999')
SELECT * FROM dual;

-- Features for HyperX Alloy FPS Pro Mechanical Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (35, 'Switch Type', 'Cherry MX Red')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (35, 'Backlighting', 'Red LED')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (35, 'Key Rollover', '6-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (35, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (35, 'Price', '7999')
SELECT * FROM dual;*/

-- Features for Ducky One 2 Mini Mechanical Keyboard
/*INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (36, 'Switch Type', 'Cherry MX Red')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (36, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (36, 'Key Rollover', '6-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (36, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (36, 'Price', '9999')
SELECT * FROM dual;

-- Features for Logitech MX Keys Wireless Illuminated Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (37, 'Switch Type', 'Membrane')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (37, 'Backlighting', 'White LED')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (37, 'Key Rollover', 'N-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (37, 'Connectivity', 'Wireless')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (37, 'Price', '9999')
SELECT * FROM dual;

-- Features for Corsair K70 RGB MK.2 Mechanical Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (38, 'Switch Type', 'Cherry MX Brown')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (38, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (38, 'Key Rollover', 'N-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (38, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (38, 'Price', '12999')
SELECT * FROM dual;

-- Features for Razer Huntsman Elite Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (39, 'Switch Type', 'Razer Opto-Mechanical')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (39, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (39, 'Key Rollover', '10-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (39, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (39, 'Price', '14999')
SELECT * FROM dual;

-- Features for SteelSeries Apex 7 Mechanical Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (40, 'Switch Type', 'SteelSeries Red')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (40, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (40, 'Key Rollover', 'N-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (40, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (40, 'Price', '12999')
SELECT * FROM dual;*/

-- Features for HyperX Alloy FPS RGB Mechanical Gaming Keyboard
/*INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (41, 'Switch Type', 'Kailh Silver Speed')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (41, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (41, 'Key Rollover', '6-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (41, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (41, 'Price', '8999')
SELECT * FROM dual;

-- Features for Ducky One 2 Mini SF Mechanical Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (42, 'Switch Type', 'Cherry MX Red')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (42, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (42, 'Key Rollover', '6-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (42, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (42, 'Price', '10999')
SELECT * FROM dual;

-- Features for Logitech K780 Multi-Device Wireless Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (43, 'Switch Type', 'Membrane')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (43, 'Backlighting', 'White LED')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (43, 'Key Rollover', 'N-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (43, 'Connectivity', 'Wireless')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (43, 'Price', '7999')
SELECT * FROM dual;

-- Features for Corsair K55 RGB Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (44, 'Switch Type', 'Membrane')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (44, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (44, 'Key Rollover', '8-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (44, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (44, 'Price', '4999')
SELECT * FROM dual;

-- Features for Razer Cynosa V2 Gaming Keyboard
INSERT ALL
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (45, 'Switch Type', 'Membrane')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (45, 'Backlighting', 'RGB')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (45, 'Key Rollover', 'N-Key')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (45, 'Connectivity', 'Wired')
    INTO PRODUCT_FEATURES (PRODUCT_ID, FEATURE_NAME, VALUE) VALUES (45, 'Price', '7999')
SELECT * FROM dual;*/

DELETE FROM PRODUCT_FEATURES WHERE FEATURE_NAME='Price';