

/*INSERT ALL
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (1, 'Dell XPS 13', 'Laptop', 111000, 1, 'Dell', 250)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (2, 'HP Spectre x360', 'Laptop', 136000, 2, 'HP', 150)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (3, 'MacBook Air', 'Laptop', 111000, 1, 'Apple', 350)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (4, 'Lenovo ThinkPad X1', 'Laptop', 212500, 2, 'Lenovo', 100)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (5, 'Acer Swift 3', 'Laptop', 76500, 1, 'Acer', 450)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (6, 'ASUS ROG Zephyrus', 'Laptop', 238000, 2, 'ASUS', 200)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (7, 'Microsoft Surface Laptop 4', 'Laptop', 127000, 1, 'Microsoft', 300)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (8, 'LG Gram 17', 'Laptop', 127500, 2, 'LG', 50)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (9, 'Razer Blade 15', 'Laptop', 152000, 1, 'Razer', 400)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (10, 'Lenovo Yoga C940', 'Laptop', 111000, 2, 'Lenovo', 150)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (11, 'HP Envy x360', 'Laptop', 85000, 1, 'HP', 250)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (12, 'Dell Inspiron 14', 'Laptop', 51000, 2, 'Dell', 100)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (13, 'MSI GS66 Stealth', 'Laptop', 281000, 1, 'MSI', 300)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (14, 'ASUS VivoBook S', 'Laptop', 59500, 2, 'ASUS', 200)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (15, 'Lenovo Legion 5', 'Laptop', 93100, 1, 'Lenovo', 50)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (16, 'Acer Predator Helios 300', 'Laptop', 127500, 2, 'Acer', 400)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (17, 'Dell Latitude 14', 'Laptop', 110000, 1, 'Dell', 350)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (18, 'Apple MacBook Pro 16', 'Laptop', 240000, 2, 'Apple', 100)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (19, 'HP Omen 15', 'Laptop', 170000, 1, 'HP', 450)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (20, 'ASUS TUF Gaming A15', 'Laptop', 100000, 2, 'ASUS', 300)
SELECT * FROM dual;*/

--monitors

/*INSERT ALL
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (21, 'Dell Ultrasharp U2419H', 'Monitor', 25000, 1, 'Dell', 150)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (22, 'HP Pavilion 22cwa', 'Monitor', 8500, 2, 'HP', 100)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (23, 'LG 27GL83A-B', 'Monitor', 48000, 1, 'LG', 200)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (24, 'Acer R240HY', 'Monitor', 12000, 2, 'Acer', 50)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (25, 'ASUS VG279Q', 'Monitor', 28000, 1, 'ASUS', 120)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (26, 'Samsung Odyssey G9', 'Monitor', 150000, 2, 'Samsung', 80)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (27, 'ViewSonic XG2402', 'Monitor', 16000, 1, 'ViewSonic', 90)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (28, 'BenQ EX2780Q', 'Monitor', 35000, 2, 'BenQ', 70)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (29, 'Dell S2719DGF', 'Monitor', 42000, 1, 'Dell', 110)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (30, 'HP EliteDisplay E243', 'Monitor', 18000, 2, 'HP', 60)
SELECT * FROM dual;*/

--keyboards

/*INSERT ALL
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (31, 'Logitech G Pro X Mechanical Gaming Keyboard', 'Keyboard', 8999, 1, 'Logitech', 120)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (32, 'Corsair K95 RGB Platinum XT Mechanical Gaming Keyboard', 'Keyboard', 17999, 2, 'Corsair', 80)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (33, 'Razer BlackWidow Elite Mechanical Gaming Keyboard', 'Keyboard', 11999, 1, 'Razer', 100)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (34, 'SteelSeries Apex Pro Mechanical Gaming Keyboard', 'Keyboard', 15999, 2, 'SteelSeries', 70)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (35, 'HyperX Alloy FPS Pro Mechanical Gaming Keyboard', 'Keyboard', 7999, 1, 'HyperX', 150)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (36, 'Ducky One 2 Mini Mechanical Keyboard', 'Keyboard', 9999, 2, 'Ducky', 120)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (37, 'Logitech MX Keys Wireless Illuminated Keyboard', 'Keyboard', 9999, 1, 'Logitech', 200)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (38, 'Corsair K70 RGB MK.2 Mechanical Gaming Keyboard', 'Keyboard', 12999, 2, 'Corsair', 90)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (39, 'Razer Huntsman Elite Gaming Keyboard', 'Keyboard', 14999, 1, 'Razer', 80)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (40, 'SteelSeries Apex 7 Mechanical Gaming Keyboard', 'Keyboard', 12999, 2, 'SteelSeries', 100)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (41, 'HyperX Alloy FPS RGB Mechanical Gaming Keyboard', 'Keyboard', 8999, 1, 'HyperX', 120)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (42, 'Ducky One 2 Mini SF Mechanical Keyboard', 'Keyboard', 10999, 2, 'Ducky', 80)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (43, 'Logitech K780 Multi-Device Wireless Keyboard', 'Keyboard', 7999, 1, 'Logitech', 150)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (44, 'Corsair K55 RGB Gaming Keyboard', 'Keyboard', 4999, 2, 'Corsair', 120)
    INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, WARRANTY, MANUFACTURER, CENTRAL_STOCK) VALUES (45, 'Razer Cynosa V2 Gaming Keyboard', 'Keyboard', 7999, 1, 'Razer', 100)
SELECT * FROM dual;*/
