--PURCHASE ORDERS SEQUENCE

-- CREATE SEQUENCE PURCHASE_ORDER_ID_SEQ 
-- INCREMENT BY 1
-- START WITH 1;
-- 
-- CREATE SEQUENCE TRANSACTION_ID_SEQ 
-- INCREMENT BY 1
-- START WITH 1;

-- CREATE SEQUENCE LOCATION_ID_SEQ
-- INCREMENT BY 1
-- START WITH 1
-- MAXVALUE 500
-- NOCYCLE;

-- CREATE SEQUENCE PAYMENT_INFO_ID_SEQ
-- INCREMENT BY 1
-- START WITH 101
-- MAXVALUE 1000
-- NOCYCLE;
