CREATE TABLE SUPPLIERS(
SUPPLIER_ID NUMBER CONSTRAINT SUPPLIER_PK PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
STREET_ADDRESS VARCHAR2(100),
POSTAL_CODE VARCHAR2(20),
CITY VARCHAR2(20),
STATE_PROVINCE VARCHAR2(50),
COUNTRY VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(100),
PHONE_NO VARCHAR2(30),
URL VARCHAR(200),
AVG_DELIVERY_TIME VARCHAR2(50));


ALTER TABLE FINANCIAL_TRANSACTIONS ADD PLACEMENT_DATE DATE;