CREATE TABLE LOCATIONS(
LOCATION_ID NUMBER CONSTRAINT LOCATIONS_PK PRIMARY KEY,
STREET_ADDRESS VARCHAR2(100),
POSTAL_CODE VARCHAR2(20),
CITY VARCHAR2(20),
STATE_PROVINCE VARCHAR2(50),
COUNTRY VARCHAR2(20) 
);

CREATE TABLE PAYMENT_INFO(
ID NUMBER CONSTRAINT PAY_PK PRIMARY KEY,
ACCOUNT_NUMBER VARCHAR2(30) NOT NULL,
ACCOUNT_HOLDER VARCHAR2(255),
BANK_NAME VARCHAR2(255) NOT NULL,
IBAN VARCHAR2(34),
CONSTRAINT PAYMENT_UNQ UNIQUE(ACCOUNT_NUMBER,BANK_NAME)
);  


CREATE TABLE SUPPLIERS(
SUPPLIER_ID NUMBER CONSTRAINT SUPPLIER_PK PRIMARY KEY,
SUPPLIER_NAME VARCHAR2(50) NOT NULL,
PICKUP_LOCATION_ID NUMBER ,--CONSTRAINT LOC_FK FOREIGN KEY REFERENCES LOCATIONS(LOCATION_ID),
PAYMENT_INFO_ID NUMBER,-- CONSTRAINT PAY_FK FOREIGN KEY REFERENCES PAYMENT_INFO(ID),
CITY VARCHAR2(20),
COUNTRY VARCHAR2(20) NOT NULL,
URL VARCHAR(200),
AVG_DELIVERY_TIME NUMBER,
CONSTRAINT LOC_FK FOREIGN KEY(PICKUP_LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID),
CONSTRAINT PAY_FK FOREIGN KEY(PAYMENT_INFO_ID) REFERENCES PAYMENT_INFO(ID),
CONSTRAINT S_UNQ UNIQUE(SUPPLIER_NAME,COUNTRY)
);


CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER CONSTRAINT PRODUCT_PK PRIMARY KEY,
PRODUCT_NAME VARCHAR2(100) NOT NULL,
CATEGORY VARCHAR2(20),
PRICE NUMBER NOT NULL CHECK (PRICE>=0), 
WARRANTY NUMBER CHECK (WARRANTY>=0),
MANUFACTURER VARCHAR2(50),
CENTRAL_STOCK NUMBER DEFAULT 0
);

CREATE TABLE PRODUCT_FEATURES(
PRODUCT_ID NUMBER CONSTRAINT PID_FK REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
FEATURE_NAME VARCHAR2(30) NOT NULL,
VALUE VARCHAR2(30),
CONSTRAINT PK PRIMARY KEY(PRODUCT_ID, FEATURE_NAME)
);

CREATE TABLE FINANCIAL_TRANSACTIONS(
TRANSACTION_ID NUMBER CONSTRAINT TRANSACTION_PK PRIMARY KEY,
TYPE VARCHAR2(50),
METHOD VARCHAR2(50),
FROM_ACCOUNT NUMBER,
TO_ACCOUNT NUMBER, 
STATUS VARCHAR2(20),
CURRENCY VARCHAR2(20),
AMOUNT NUMBER(15),
CONSTRAINT FROM_FK FOREIGN KEY(FROM_ACCOUNT) REFERENCES PAYMENT_INFO(ID) ON DELETE SET NULL,
CONSTRAINT TO_FK FOREIGN KEY(TO_ACCOUNT) REFERENCES PAYMENT_INFO(ID) ON DELETE SET NULL
);

CREATE TABLE TRANSPORT_COMPANIES(
COMPANY_ID NUMBER CONSTRAINT TRANSPORT_PK PRIMARY KEY,
NAME VARCHAR2(100) NOT NULL UNIQUE,
ADDRESS NUMBER, 
PAYMENT_ID NUMBER, 
CONSTRAINT TLOC_FK FOREIGN KEY(ADDRESS) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE  SET NULL,
CONSTRAINT BANK_FK  FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT_INFO(ID) ON DELETE SET NULL
);

CREATE TABLE SHIPMENTS(
SHIPMENT_ID NUMBER CONSTRAINT SHIPMENT_PK PRIMARY KEY,
TRANSPORT_COMPANY_ID NUMBER,
REQUSITION_TYPE VARCHAR2(50),
DEPARTURE_TIME VARCHAR2(20),
DEPARTURE_DATE DATE,
ARRIVAL_TIME VARCHAR2(20),
ARRIVAL_DATE DATE,
VEHICLE_NO VARCHAR2(20),
CURRENT_LOCATION VARCHAR2(255),
START_LOCATION NUMBER,
DESTINATION NUMBER,
TRANSACTION_ID NUMBER,
 CONSTRAINT COMPANY_FK  FOREIGN KEY(TRANSPORT_COMPANY_ID) REFERENCES TRANSPORT_COMPANIES(COMPANY_ID) ON DELETE SET NULL,
 CONSTRAINT SHIPFROM_FK FOREIGN KEY(START_LOCATION) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE SET NULL,
  CONSTRAINT SHIPTO_FK FOREIGN KEY(DESTINATION) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE SET NULL ,
  CONSTRAINT TRANSACTION_FK FOREIGN KEY(TRANSACTION_ID) REFERENCES FINANCIAL_TRANSACTIONS(TRANSACTION_ID) ON DELETE SET NULL
);

CREATE TABLE SUPPLIER_PRODUCT(
SUPPLIER_ID NUMBER, 
PRODUCT_ID NUMBER, 
CONSTRAINT SP_PK PRIMARY KEY(SUPPLIER_ID, PRODUCT_ID) ,
CONSTRAINT SUP_FK FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID) ON DELETE CASCADE,
CONSTRAINT PRO_SUP_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);

CREATE TABLE PURCHASE_ORDERS(
ORDER_ID NUMBER CONSTRAINT PURCHASE_PK PRIMARY KEY,
SUPPLIER_ID NUMBER, 
PLACEMENT_DATE DATE DEFAULT SYSDATE, 
PICKUP_DATE DATE,
TRANSACTION_ID NUMBER,
SHIPMENT_ID NUMBER,
 CONSTRAINT PO_SHIP_FK FOREIGN KEY(SHIPMENT_ID) REFERENCES SHIPMENTS(SHIPMENT_ID) ON DELETE SET NULL,
CONSTRAINT SUP_PO_FK FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID) ON DELETE SET NULL, 
 CONSTRAINT PO_PAY_FK FOREIGN KEY(TRANSACTION_ID) REFERENCES FINANCIAL_TRANSACTIONS(TRANSACTION_ID) ON DELETE SET NULL
);

CREATE TABLE PURCHASE_ORDER_PRODUCTS(
ORDER_ID NUMBER,
PRODUCT_ID NUMBER,
QUANTITY NUMBER CONSTRAINT Q_NUM CHECK (QUANTITY>0),
CONSTRAINT POP_PK PRIMARY KEY(ORDER_ID,PRODUCT_ID),
 CONSTRAINT PO_ORDER_FK FOREIGN KEY(ORDER_ID) REFERENCES PURCHASE_ORDERS(ORDER_ID) ON DELETE CASCADE,
  CONSTRAINT PO_PRODUCT_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);


 CREATE TABLE CLIENT_ORDERS(
 ORDER_ID NUMBER CONSTRAINT CL_ORDER_ID PRIMARY KEY,
 CLIENT_ID NUMBER ,
 PLACEMENT_DATE DATE DEFAULT SYSDATE,
 SHIPMENT_ID NUMBER,
 TRANSACTION_ID NUMBER,
 CONSTRAINT CLIENT_FK FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT_COMPANIES(CLIENT_ID) ON DELETE SET NULL,
 CONSTRAINT SHIP_CO_FK FOREIGN KEY(SHIPMENT_ID) REFERENCES SHIPMENTS(SHIPMENT_ID) ON DELETE SET NULL,
 CONSTRAINT PAY_CO_FK FOREIGN KEY(TRANSACTION_ID) REFERENCES FINANCIAL_TRANSACTIONS(TRANSACTION_ID) ON DELETE SET NULL
 );

CREATE TABLE CLIENT_ORDER_PRODUCTS(
ORDER_ID NUMBER,
PRODUCT_ID NUMBER, 
QUANTITY NUMBER CHECK(QUANTITY>0),
CONSTRAINT C_ORDER_FK FOREIGN KEY(ORDER_ID) REFERENCES CLIENT_ORDERS(ORDER_ID) ON DELETE CASCADE,
CONSTRAINT CO_PRODUCT_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
CONSTRAINT COP_PK PRIMARY KEY(ORDER_ID,PRODUCT_ID)
);


CREATE TABLE BRANCHES(
BRANCH_ID NUMBER CONSTRAINT BRANCH_PK PRIMARY KEY,
ADDRESS NUMBER,
MANAGER VARCHAR2(50),
SQUARE_FOOTAGE NUMBER,
AVG_SHIPPING_DURATION NUMBER,
CONSTRAINT LOCATION_FK FOREIGN KEY(ADDRESS) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE SET NULL
);

CREATE TABLE BRANCH_INCOME_STATEMENT(
BRANCH_ID NUMBER,
START_DATE DATE,
END_DATE DATE,
EARNINGS NUMBER,    
OVERHEAD NUMBER,
REPORT_DOCUMENT BLOB ,
CONSTRAINT BRANCH_INCOME_FK FOREIGN KEY(BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID) ON DELETE CASCADE,
CONSTRAINT REPORT_PK PRIMARY KEY(BRANCH_ID, START_DATE)
);

CREATE TABLE SUPPLY_REQUESTS(
REQUEST_ID NUMBER CONSTRAINT REQUEST_PK PRIMARY KEY,
BRANCH_ID NUMBER, 
PLACEMENT_DATE DATE DEFAULT SYSDATE,
DEADLINE DATE,
STATUS VARCHAR2(20),
CONSTRAINT SR_BRANCH_FK FOREIGN KEY(BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID) ON DELETE CASCADE
);

CREATE TABLE SUPPLY_REQUEST_PRODUCTS(
REQUEST_ID NUMBER,
PRODUCT_ID NUMBER,
CONSTRAINT SR_PK PRIMARY KEY(REQUEST_ID,PRODUCT_ID),
QUANTITY NUMBER CHECK(QUANTITY>0),
CONSTRAINT REQUEST_FK FOREIGN KEY(REQUEST_ID) REFERENCES SUPPLY_REQUESTS(REQUEST_ID) ON DELETE CASCADE,
CONSTRAINT SR_PRODUCT_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);

CREATE TABLE CONFIRMED_SUPPLY(
SUPPLY_ID NUMBER CONSTRAINT SUPPLY_PK PRIMARY KEY,
REQUEST_ID NUMBER,
SHIPMENT_ID NUMBER,
CONSTRAINT CR_REQUEST_FK FOREIGN KEY(REQUEST_ID) REFERENCES SUPPLY_REQUESTS(REQUEST_ID) ON DELETE CASCADE,
CONSTRAINT CR_SHIPMENT_FK FOREIGN KEY(SHIPMENT_ID) REFERENCES SHIPMENTS(SHIPMENT_ID) ON DELETE SET NULL
);

CREATE TABLE CONFIRMED_SUPPLY_PRODUCTS(
SUPPLY_ID NUMBER, 
PRODUCT_ID NUMBER, 
QUANTITY NUMBER CHECK(QUANTITY>0),
CONSTRAINT SUPPLY_FK FOREIGN KEY(SUPPLY_ID) REFERENCES CONFIRMED_SUPPLY(SUPPLY_ID) ON DELETE CASCADE,
CONSTRAINT CS_PRODUCT_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
CONSTRAINT CSP_PK PRIMARY KEY(SUPPLY_ID,PRODUCT_ID)
);

